### ISSUE TITLE
BicubicResample() and tiny height

### ISSUE THREAD

**Issue by tomwiel** [AngusJohnson/Image32#52] opened 2024-04-08 08:37 UTC
A tiny img-height (at least the case of 1 pixel) can cause pi being out of range in img.Pixels[pi].

**Comment by AngusJohnson** [comment] 2024-04-08 21:40
I suspect the problem isn't in the BicubicResample function but in its calling function.
What is the size of your source image, and what is the size of the intended target (ie resized) image?

**Comment by tomwiel** [comment] 2024-04-09 04:22
The SrcImg has (width = 100), (height = 1). The (unoptimized) call is like this:
```pascal
if (x256 >= 0) and (x256 < srcImg.width*256) and (y256 >= 0) and (y256 < srcImg.height*256) then begin
    if (y256 < 256) then y256 := 100; // ensure color of 1st line
    srcColor := resampler(srcImg, x256, y256);  
end;
```

**Comment by AngusJohnson** [comment] 2024-04-09 10:03
Thanks. While investigating this I've discovered that my resampling code need significant revision, and that will likely take a few days.

**Comment by AngusJohnson** [comment] 2024-04-12 22:04
This should be fixed in the latest revision (where I've signficant;ly improved resampling of image edges).

**Closed by AngusJohnson** 2024-04-12 22:04 UTC
